functions:
  get-applications:
    handler: handlers/applicationHandlers.getApplications
    events:
      - httpApi:
          path: /applications
          method: get
          authorizer:
            type: jwt
            name: EsenciaAuthorizer

  get-application-by-id:
    handler: handlers/applicationHandlers.getApplication
    events:
      - httpApi:
          path: /applications/{id}
          method: get
          authorizer:
            type: jwt
            name: EsenciaAuthorizer

  create-application:
    handler: handlers/applicationHandlers.createApplication
    events:
      - httpApi:
          path: /applications
          method: POST
          authorizer:
            type: jwt
            name: EsenciaAuthorizer
