functions:
  get-application-by-id:
    handler: handlers/applicationHandlers.getApplication
    events:
      - httpApi:
          path: /applications/{id}
          method: get
          authorizer:
            type: jwt
            id: ${cf:core-service-${self:provider.stage}.EsenciaAuthorizerId}
