# "org" ensures this Service is used with the correct Serverless Framework Access Key.
##org: esenciaestudios
# "service" is the name of this project. This will also be added to your AWS resource names.
service: core-service

provider:
  name: aws
  runtime: nodejs20.x
  profile: esencia
  timeout: 120
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: esencia-backend-deployment
    serverSideEncryption: AES256
    blockPublicAccess: true

  role: arn:aws:iam::${aws:accountId}:role/lambda-role-execution
  #vpc:
  #  securityGroupIds:
  #    - sg-083d8b2d9ba91627a
  #  subnetIds:
  #    - subnet-00a83d29f11333109
  #    - subnet-0fe2c0c7efdd332c9
  #    - subnet-0e71dc73600fde75a
  #    - subnet-0001da65ac21b3935
  #    - subnet-050448c98ab862173
  #    - subnet-0912aaf196b1f0adb

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - secretsmanager:GetSecretValue
        - ssm:GetParameters
        - s3:PutObject
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:InitiateAuth
        - cognito-idp:RespondToAuthChallenge
        - cognito-idp:GetUser
        - cognito-idp:ListUsers
      Resource: "*"

  environment:
    REGION: ${self:provider.region}
    DB_HOST: ${env:DB_HOST}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    DB_PORT: ${env:DB_PORT}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_CLIENT_SECRET: ${env:COGNITO_CLIENT_SECRET}
    STAGE: ${self:provider.stage}

  httpApi:
    #id: ${cf:core-service-{self:stage}.HttpApiId}
    authorizers:
      EsenciaAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${env:COGNITO_USER_POOL_ID}
        audience:
          - ${env:COGNITO_CLIENT_ID}

  layers:
    - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:BackendEsenciaLayer:3

#resources:
#  Resources:
#    HttpApi:
#      Type: AWS::ApiGatewayV2::Api
#      Properties:
#        Name: EsenciaHttpApi
#        ProtocolType: HTTP
#
#  Outputs:
#    HttpApiId:
#      Value: !Ref HttpApi
#      Export:
#        Name: HttpApiId-${self:provider.stage}

functions:
  - ${file(./functions/suscription.yml):functions}
  - ${file(./functions/users.yml):functions}
  - ${file(./functions/rolesPermissions.yml):functions}
  - ${file(./functions/applications.yml):functions}
  - ${file(./functions/auth.yml):functions}
  - ${file(./functions/dynamicRoutes.yml):functions}
  - ${file(./functions/menuItems.yml):functions}
  - ${file(./functions/accessLogs.yml):functions}
  - ${file(./functions/timeTrackers.yml):functions}
  - ${file(./functions/request.yml):functions}
  - ${file(./functions/organization.yml):functions}
  - ${file(./functions/payment.yml):functions}
  - ${file(./functions/planFeature.yml):functions}

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 4000

plugins:
  - serverless-offline

package:
  patterns:
    - "!layer.zip"
    - "!layer/**"
    - "!.git/**"
    - "!.env"
    - "!test/**"
    - "!jest.config.js"
    - "!bitbucket-pipelines.yml"
    - "!node_modules/**"
    - "!.serverless/**"
    - "!README.md"
    - "!initDB.js"
